# Generated by Django 3.1.4 on 2020-12-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app9_tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorrequest',
            options={'verbose_name': 'Tutor Request',
                     'verbose_name_plural': 'Tutor Requests'},
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='words_list',
            field=models.CharField(
                default='[<django.db.models.fields.CharField>, <django.db.models.fields.CharField>, <django.db.models.fields.CharField>, <django.db.models.fields.CharField>, <django.db.models.fields.CharField>]', max_length=500, verbose_name='wordlist'),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='question_txt',
            field=models.TextField(
                max_length=1024, verbose_name='tutor_req_txt'),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='request_dt',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='tutor_req_datetime'),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='title',
            field=models.CharField(
                max_length=64, verbose_name='tutor_req_title'),
        ),
        migrations.AlterModelTable(
            name='tutorrequest',
            table='tutor_request',
        ),
    ]
