# Generated by Django 3.1.4 on 2020-12-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app9_tutoring', '0003_auto_20201217_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrequest',
            name='word2',
            field=models.CharField(
                max_length=64, null=True, verbose_name='word2'),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='word3',
            field=models.CharField(
                max_length=64, null=True, verbose_name='word3'),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='word4',
            field=models.CharField(
                max_length=64, null=True, verbose_name='word4'),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='word5',
            field=models.CharField(
                max_length=64, null=True, verbose_name='word5'),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='words_list',
            field=models.CharField(
                max_length=500, null=True, verbose_name='wordlist'),
        ),
    ]
