# Generated by Django 3.1.4 on 2020-12-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='userid', max_length=64, verbose_name='userid')),
                ('wordid', models.CharField(max_length=64, verbose_name='wordid')),
                ('wordmemo', models.CharField(max_length=64, verbose_name='wordmemo')),
                ('memo_dt', models.DateTimeField(auto_now_add=True, verbose_name='added_datetime')),
            ],
            options={
                'verbose_name': 'Duo Read User WordMemo',
                'verbose_name_plural': 'Duo Read User WordMemos',
                'db_table': 'wordmemo',
            },
        ),
    ]
