# Generated by Django 3.1.4 on 2020-12-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3_wordbook', '0002_auto_20201217_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordmemo',
            options={'verbose_name': 'WordMemo',
                     'verbose_name_plural': 'WordMemos'},
        ),
    ]
