# Generated by Django 3.1.4 on 2020-12-25 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app3_wordbook', '0003_auto_20201217_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordMemoCn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.CharField(max_length=64, verbose_name='word_id')),
                ('memo_txt', models.CharField(default='', max_length=64, verbose_name='memo_text')),
                ('add_dt', models.DateTimeField(auto_now_add=True, verbose_name='added_datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='updated_datetime')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WordMemo',
                'verbose_name_plural': 'WordMemos',
                'db_table': 'wordmemo_cn',
            },
        ),
        migrations.DeleteModel(
            name='WordMemo',
        ),
    ]
