# Generated by Django 3.1.4 on 2020-12-26 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app7_dictionary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app3_wordbook', '0005_auto_20201226_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordsCn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_mark', models.CharField(default='', max_length=64, verbose_name='word_mark')),
                ('add_dt', models.DateTimeField(auto_now_add=True, verbose_name='added_datetime')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='updated_datetime')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app7_dictionary.dictionarycn')),
            ],
            options={
                'verbose_name': "user's word mark",
                'verbose_name_plural': 'user wordbook',
                'db_table': 'userwords_cn',
            },
        ),
    ]
