# Generated by Django 3.1.4 on 2020-12-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_wordbook', '0006_userwordscn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmemocn',
            name='memo_txt',
            field=models.CharField(default='', max_length=100, verbose_name='memo_text'),
        ),
    ]
