# Generated by Django 3.1.4 on 2020-12-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64, verbose_name='last name')),
                ('first_name', models.CharField(max_length=64, verbose_name='first name')),
                ('email', models.CharField(max_length=64, verbose_name='password')),
                ('mobile', models.CharField(max_length=64, verbose_name='password')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('birthdate', models.DateField(verbose_name='birth date')),
                ('gender', models.CharField(max_length=32, verbose_name='password')),
                ('join_dt', models.DateTimeField(auto_now_add=True, verbose_name='joined_datetime')),
            ],
        ),
    ]
