# Generated by Django 3.1.4 on 2020-12-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'Duo Read User Account',
                     'verbose_name_plural': 'Duo Read User Accounts'},
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.CharField(max_length=64, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(max_length=32, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='mobile',
            field=models.CharField(max_length=64, verbose_name='mobile'),
        ),
        migrations.AlterModelTable(
            name='useraccount',
            table='user_account',
        ),
    ]
