# Generated by Django 3.1.4 on 2020-12-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_user_accounts', '0002_auto_20201211_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='userid',
            field=models.CharField(
                default='userid', max_length=64, verbose_name='userid'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(
                default='username', max_length=64, verbose_name='username'),
            preserve_default=False,
        ),
    ]
