# Generated by Django 3.1.4 on 2020-12-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_user_accounts', '0005_auto_20201217_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='mobile',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='join_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='join_dt'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(default='password', max_length=32, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='userid',
            field=models.EmailField(default='userid', max_length=32, unique=True, verbose_name='userid'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=32, verbose_name='username'),
        ),
    ]
