# Generated by Django 3.1.4 on 2020-12-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_user_accounts', '0006_auto_20201221_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='userid',
            new_name='email',
        ),
    ]
