# Generated by Django 3.1.4 on 2020-12-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_user_accounts', '0008_auto_20201221_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(default='email', max_length=32, unique=True, verbose_name='email'),
        ),
    ]
