# Generated by Django 3.1.4 on 2020-12-26 07:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2_user_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_mode', models.CharField(default='default theme', max_length=32, verbose_name='screen mode')),
                ('txt_size', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(25)], verbose_name='text size')),
                ('dict_size', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(25)], verbose_name='dict text size')),
                ('notice_on', models.BooleanField(default=False)),
                ('sms_agree', models.BooleanField(default=False)),
                ('email_agree', models.BooleanField(default=False)),
                ('set_dt', models.DateTimeField(auto_now_add=True, verbose_name='setting modified at')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User App Setting',
                'verbose_name_plural': 'User App Settings',
                'db_table': 'user_app_setting',
            },
        ),
    ]
