# Generated by Django 3.1.4 on 2020-12-26 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_user_settings', '0003_auto_20201226_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='dict_size',
            field=models.DecimalField(decimal_places=1, default=11, max_digits=3, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(25)], verbose_name='dict_text_size'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='txt_size',
            field=models.DecimalField(decimal_places=1, default=12, max_digits=3, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(25)], verbose_name='text_size'),
        ),
    ]
