# Generated by Django 3.1.4 on 2020-12-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1_user_accounts', '0004_auto_20201211_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(
                    max_length=64, verbose_name='request_title')),
                ('word1', models.CharField(max_length=64, verbose_name='word1')),
                ('word2', models.CharField(max_length=64, verbose_name='word2')),
                ('word3', models.CharField(max_length=64, verbose_name='word3')),
                ('word4', models.CharField(max_length=64, verbose_name='word4')),
                ('word5', models.CharField(max_length=64, verbose_name='word5')),
                ('question_txt', models.CharField(
                    max_length=1024, verbose_name='request_txt')),
                ('request_dt', models.DateTimeField(
                    auto_now_add=True, verbose_name='request_datetime')),
                ('userid', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT, to='app1_user_accounts.useraccount')),
            ],
        ),
    ]
