# Generated by Django 3.1.4 on 2020-12-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='email', max_length=32, unique=True, verbose_name='email')),
                ('enroll_dt', models.DateTimeField(auto_now_add=True, verbose_name='join_dt')),
            ],
            options={
                'verbose_name': 'Mailing Enroll',
                'verbose_name_plural': 'Mailing List',
                'db_table': 'mailing',
            },
        ),
    ]
