# Generated by Django 3.1.4 on 2020-12-17 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1_user_accounts', '0004_auto_20201211_2031'),
        ('app3_wordbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmemo',
            name='userid',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='app1_user_accounts.useraccount'),
        ),
    ]
