# Generated by Django 3.1.4 on 2020-12-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_wordbook', '0007_auto_20201226_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwordscn',
            options={'verbose_name': 'User Marked Word', 'verbose_name_plural': 'User WordBook'},
        ),
        migrations.AddField(
            model_name='userwordscn',
            name='memo_txt',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='memo_text'),
        ),
        migrations.AlterField(
            model_name='userwordscn',
            name='update_dt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='updated_datetime'),
        ),
        migrations.AlterField(
            model_name='userwordscn',
            name='word_mark',
            field=models.CharField(choices=[('V', 'Viewed'), ('U', 'Unknown'), ('K', 'Known'), ('C', 'Confusing')], default='V', max_length=1, verbose_name='word_mark'),
        ),
    ]
