# Generated by Django 3.1.4 on 2020-12-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_wordbook', '0008_auto_20201231_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordscn',
            name='word_context',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='word_context'),
        ),
        migrations.DeleteModel(
            name='WordMemoCn',
        ),
    ]
