# Generated by Django 3.1.4 on 2021-01-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_wordbook', '0009_auto_20201231_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwordscn',
            name='memo_txt',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='memo_text'),
        ),
        migrations.AlterField(
            model_name='userwordscn',
            name='word_context',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='word_context'),
        ),
    ]
