# Generated by Django 3.1.4 on 2020-12-25 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_lang', models.CharField(default='native_lang', max_length=32, verbose_name='native_lang')),
                ('target_lang1', models.CharField(default='target_lang1', max_length=32, verbose_name='target_lang1')),
                ('target_lang2', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='target_lang2')),
                ('set_dt', models.DateTimeField(auto_now_add=True, verbose_name='set_dt')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Language',
                'verbose_name_plural': 'User Languages',
                'db_table': 'user_languages',
            },
        ),
    ]
