# Generated by Django 3.1.4 on 2020-12-26 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_user_settings', '0002_appsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='dict_size',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(25)], verbose_name='dict_text_size'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='screen_mode',
            field=models.CharField(default='default_theme', max_length=32, verbose_name='screen_mode'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='txt_size',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(25)], verbose_name='text_size'),
        ),
    ]
