# Generated by Django 3.1.4 on 2020-12-29 21:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2_user_settings', '0004_auto_20201226_2009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLanguage',
            new_name='LangSetting',
        ),
    ]
