# Generated by Django 3.1.4 on 2021-01-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_user_settings', '0005_auto_20201230_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='screen_mode',
            field=models.CharField(choices=[('DF', 'Default'), ('DK', 'Dark'), ('BR', 'Light')], default='default_theme', max_length=2, verbose_name='screen_mode'),
        ),
        migrations.AlterField(
            model_name='langsetting',
            name='native_lang',
            field=models.CharField(choices=[('CN', 'Chinese'), ('KR', 'Korean'), ('EN', 'English')], default='native_lang', max_length=2, verbose_name='native_lang'),
        ),
        migrations.AlterField(
            model_name='langsetting',
            name='target_lang1',
            field=models.CharField(choices=[('CN', 'Chinese'), ('KR', 'Korean'), ('EN', 'English')], default='CN', max_length=2, verbose_name='target_lang1'),
        ),
        migrations.AlterField(
            model_name='langsetting',
            name='target_lang2',
            field=models.CharField(blank=True, choices=[('CN', 'Chinese'), ('KR', 'Korean'), ('EN', 'English')], default='EN', max_length=2, null=True, verbose_name='target_lang2'),
        ),
    ]
