# Generated by Django 3.1.4 on 2020-12-27 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_grade', models.CharField(default='none_payment', max_length=64, verbose_name='member_grade')),
                ('word_mark_limit', models.IntegerField(default=100, verbose_name='word_mark_limit')),
                ('word_memo_limit', models.IntegerField(default=100, verbose_name='word_memo_limit')),
                ('doc_import_limit', models.IntegerField(default=5, verbose_name='doc_import_limit')),
                ('doc_max_size', models.IntegerField(default=10485760, verbose_name='doc_max_size')),
            ],
            options={
                'verbose_name': 'usage limit level',
                'verbose_name_plural': 'usage limit settings',
                'db_table': 'usage_limit',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribtion_type', models.CharField(default='subscribtion_type', max_length=64, verbose_name='subscribtion_type')),
                ('payment_type', models.CharField(default='payment_type', max_length=64, verbose_name='payment_type')),
                ('auto_extension', models.BooleanField(default=False)),
                ('start_dt', models.DateTimeField(auto_now_add=True, verbose_name='start_dt')),
                ('end_dt', models.DateTimeField(verbose_name='end_dt')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Document',
                'verbose_name_plural': 'User Documents',
                'db_table': 'subscribtion',
            },
        ),
    ]
