# Generated by Django 3.1.4 on 2020-12-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryCn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=64, verbose_name='word')),
                ('pronounciation', models.CharField(default='', max_length=64, null=True, verbose_name='pronounciation')),
                ('definition', models.CharField(default='', max_length=64, verbose_name='definition')),
                ('word_group', models.CharField(default='', max_length=64, null=True, verbose_name='word_group')),
                ('frequency', models.CharField(default='', max_length=64, null=True, verbose_name='frequency')),
                ('topic_group', models.CharField(default='', max_length=64, null=True, verbose_name='topic_group')),
                ('manage_code', models.CharField(default='', max_length=64, verbose_name='manage_code')),
            ],
            options={
                'verbose_name': 'Word : Chinese',
                'verbose_name_plural': 'Dictionary : Chinese',
                'db_table': 'dictionary_cn',
            },
        ),
    ]
