# Generated by Django 3.1.4 on 2020-12-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionarycn',
            name='definition',
            field=models.TextField(default='', max_length=450, verbose_name='definition'),
        ),
        migrations.AlterField(
            model_name='dictionarycn',
            name='frequency',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='frequency'),
        ),
        migrations.AlterField(
            model_name='dictionarycn',
            name='manage_code',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='manage_code'),
        ),
        migrations.AlterField(
            model_name='dictionarycn',
            name='topic_group',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='topic_group'),
        ),
        migrations.AlterField(
            model_name='dictionarycn',
            name='word_group',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='word_group'),
        ),
    ]
