# Generated by Django 3.1.4 on 2021-01-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_wordbook', '0009_auto_20201231_0701'),
        ('app7_dictionary', '0002_auto_20201231_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=64, verbose_name='word')),
                ('pronounciation', models.CharField(default='', max_length=64, null=True, verbose_name='pronounciation')),
                ('definition', models.TextField(default='', max_length=450, verbose_name='definition')),
                ('word_group', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='word_group')),
                ('frequency', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='frequency')),
                ('topic_group', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='topic_group')),
                ('manage_code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='manage_code')),
            ],
            options={
                'verbose_name': 'Word : English',
                'verbose_name_plural': 'Dictionary : English',
                'db_table': 'dict_en',
            },
        ),
        migrations.RenameModel(
            old_name='DictionaryCn',
            new_name='DictCn',
        ),
        migrations.AlterModelTable(
            name='dictcn',
            table='dict_cn',
        ),
    ]
