# Generated by Django 3.1.4 on 2021-01-03 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_title', models.CharField(default='doc_title', max_length=64, verbose_name='doc_title')),
                ('msg_txt', models.CharField(default='', max_length=400, verbose_name='memo_text')),
                ('msg_code', models.CharField(default='', max_length=64, verbose_name='msg_code')),
            ],
            options={
                'verbose_name': 'original messge',
                'verbose_name_plural': 'message pool',
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_dt', models.DateTimeField(auto_now_add=True, verbose_name='sent_datetime')),
                ('view_dt', models.DateTimeField(blank=True, null=True, verbose_name='viewd_datetime')),
                ('msg_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app6_message.message')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message log',
                'verbose_name_plural': 'message logs',
                'db_table': 'message_log',
            },
        ),
    ]
