# Generated by Django 3.1.4 on 2020-12-26 13:39

import app4_docs.models
import app4_docs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4_docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocs',
            name='doc_file',
            field=models.FileField(blank=True, default='no_file', null=True, upload_to=app4_docs.models.user_doc_file_path, validators=[app4_docs.validators.validate_file_10mb], verbose_name='doc_file'),
        ),
        migrations.AlterField(
            model_name='userdocs',
            name='doc_img',
            field=models.ImageField(blank=True, default='no_img', null=True, upload_to=app4_docs.models.user_doc_img_path, validators=[app4_docs.validators.validate_file_10mb], verbose_name='doc_img'),
        ),
    ]
