# Generated by Django 3.1.4 on 2021-01-03 19:19

import app4_docs.models
import app4_docs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4_docs', '0002_auto_20201226_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocs',
            name='update_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='update_dt'),
        ),
        migrations.AlterField(
            model_name='userdocs',
            name='add_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='add_dt'),
        ),
        migrations.AlterField(
            model_name='userdocs',
            name='doc_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=app4_docs.models.user_doc_file_path, validators=[app4_docs.validators.validate_file_10mb], verbose_name='doc_file'),
        ),
        migrations.AlterField(
            model_name='userdocs',
            name='doc_group',
            field=models.CharField(choices=[('DF', 'Default group'), ('CA', 'Casual (SNS, etc.)'), ('NA', 'News Articles'), ('LI', 'Literatures'), ('AC', 'Academic article')], default='DF', max_length=2, verbose_name='doc_group'),
        ),
        migrations.AlterField(
            model_name='userdocs',
            name='doc_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=app4_docs.models.user_doc_img_path, validators=[app4_docs.validators.validate_file_10mb], verbose_name='doc_img'),
        ),
        migrations.AlterField(
            model_name='userdocs',
            name='doc_txt',
            field=models.TextField(blank=True, default='no_text_added', max_length=2048, null=True, verbose_name='doc_text'),
        ),
    ]
