# Generated by Django 3.1.4 on 2020-12-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_user_accounts', '0003_auto_20201211_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(
                max_length=32, null=True, verbose_name='gender'),
        ),
    ]
