# Generated by Django 3.1.4 on 2020-12-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_user_accounts', '0004_auto_20201211_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'User Account',
                     'verbose_name_plural': 'User Accounts'},
        ),
    ]
