# Generated by Django 3.1.4 on 2020-12-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_user_accounts', '0007_auto_20201221_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
